### ISSUE TITLE
there is no ExplorationAction.h in micvision/include/micvision.

### ISSUE THREAD

**Issue by SillyEndless** [tyuownu/micvision#10]
would you mind add it ?please

**Comment by tyuownu** [comment]
Sorry for late.
The `ExplorationAction.h` is auto-generate by `micvision/micvision/action/Exploration.action` file. Maybe you can compile the code again to solve this issue. Thanks

**Comment by SillyEndless** [comment]
> Sorry for late.
> The `ExplorationAction.h` is auto-generate by `micvision/micvision/action/Exploration.action` file. Maybe you can compile the code again to solve this issue. Thanks

Thanks for your reply.I will try it some time later.

**Comment by tyuownu** [comment]
Closed

**Comment by tyuownu** [comment]
Please check the [solution](https://github.com/tyuownu/micvision/commit/58e0813edef865a02b4ef121d75c8a77bfc10cb3), thanks.
